package lt.bumbis.rpsim.demo

import org.drools.runtime.process.WorkflowProcessInstance

rule "Unknown Customer" ruleflow-group "Validation"
    when
        r: Request()
        not Person(id == r.personId)
    then
        r.setInvalid("Unknown customer");
end

rule "Underage Customer" ruleflow-group "Validation"
    when
        r: Request()
        Person(id == r.personId, age < 100)
    then
        r.setInvalid("Underage customer");        
end